variables:
  ARM_PASS: $(adminpass)

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.network/azure-bastion'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMME'
    subscriptionId: 'b66b74fc-2422-48d8-ab44-3321a3f0a023' 
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'az-400-2'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-webAppName martinswebapp20211108'
    #-administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'

